In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv(r"C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\data\Processed\clean_car_listing.csv")
df.head()

,Fuel_Type,Transmission,Clean_Price,Clean_Kilometers,Brand,Model,Car_Age,Km_per_Year
0,Petrol,Manual,172000,43518,Hyundai,Eon,11,3626.500000
1,Petrol,Manual,239000,42678,Maruti,Wagon R 1.0,9,4267.800000
2,CNG,Manual,164000,60214,Datsun,Redi Go,8,6690.444444
3,Petrol,Manual,520000,50912,Tata,NEXON,6,7273.142857
4,Petrol,Manual,250000,68431,Renault,Kwid,6,9775.857143

In [4]:
df.isnull().sum()

Fuel_Type           0
Transmission        0
Clean_Price         0
Clean_Kilometers    0
Brand               0
Model               0
Car_Age             0
Km_per_Year         0
dtype: int64

In [5]:
df['Brand'].nunique()

24

In [6]:
df['Model'] = df['Model'].astype(str).str.strip().str.lower()
df['Transmission'] = df['Transmission'].astype(str).str.strip().str.lower()
df['Fuel_Type'] = df['Fuel_Type'].astype(str).str.strip().str.lower()
df['Brand'] = df['Brand'].astype(str).str.strip().str.lower()
df['Make_Model'] = df['Brand'].str.strip() + "_" + df['Model'].str.strip()      #Combined Company and model

In [7]:
df.head()

,Fuel_Type,Transmission,Clean_Price,Clean_Kilometers,Brand,Model,Car_Age,Km_per_Year,Make_Model
0,petrol,manual,172000,43518,hyundai,eon,11,3626.500000,hyundai_eon
1,petrol,manual,239000,42678,maruti,wagon r 1.0,9,4267.800000,maruti_wagon r 1.0
2,cng,manual,164000,60214,datsun,redi go,8,6690.444444,datsun_redi go
3,petrol,manual,520000,50912,tata,nexon,6,7273.142857,tata_nexon
4,petrol,manual,250000,68431,renault,kwid,6,9775.857143,renault_kwid

In [6]:
q = pd.qcut(df['Clean_Price'], q=10, labels=False, duplicates='drop')

y = df['Clean_Price']
X = df.drop(columns=["Clean_Price"])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=q)

print(f"Training data Shape: {X_train.shape}")
print(f"Testing data Shape: {X_test.shape}")

Training data Shape: (3406, 8)
Testing data Shape: (852, 8)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, TargetEncoder

In [8]:
df.head()

,Fuel_Type,Transmission,Clean_Price,Clean_Kilometers,Brand,Model,Car_Age,Km_per_Year,Make_Model
0,petrol,manual,172000,43518,hyundai,eon,11,3626.500000,hyundai_eon
1,petrol,manual,239000,42678,maruti,wagon r 1.0,9,4267.800000,maruti_wagon r 1.0
2,cng,manual,164000,60214,datsun,redi go,8,6690.444444,datsun_redi go
3,petrol,manual,520000,50912,tata,nexon,6,7273.142857,tata_nexon
4,petrol,manual,250000,68431,renault,kwid,6,9775.857143,renault_kwid

In [ ]:
low_card_features = ['Fuel_Type','Transmission']
numeric_features = ['Car_Age', 'Clean_Kilometers', 'Km_per_Year']
high_card_features = ['Make_Model']             

numeric_transformer = Pipeline(steps=[("Scaler", StandardScaler())])
low_card_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])
high_card_transformer = Pipeline(steps=[
    ('target_enc',TargetEncoder(smooth='auto',cv=5))
])                 

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features),
    ('low_card', low_card_transformer, low_card_features),
    ('high_card',high_card_transformer,high_card_features)
])

In [10]:
import xgboost as xgb
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.compose import TransformedTargetRegressor

In [11]:
ridge_base = Ridge()
ridge_tt = TransformedTargetRegressor(regressor=ridge_base, func=np.log1p, inverse_func=np.expm1)

ridge_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', ridge_tt)
])
ridge_param_grid = {
    'regressor__regressor__alpha': [0.01, 0.1, 1.0, 10.0,50.0]
}
ridge_grid = GridSearchCV(ridge_pipe, ridge_param_grid, cv=3, scoring='neg_mean_absolute_error', n_jobs=-1)
ridge_grid.fit(X_train, y_train)
print(f"Best Ridge params: {ridge_grid.best_params_}")

c:\Programming\Machine Learning\Used Car Price Intelligence\.venv\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

Best Ridge params: {'regressor__regressor__alpha': 0.01}

In [12]:
rf_base = RandomForestRegressor(random_state=42)
rf_tt = TransformedTargetRegressor(regressor=rf_base, func=np.log1p, inverse_func=np.expm1)
rf_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', rf_tt)
])
rf_param_grid = {
    'regressor__regressor__n_estimators': [50, 100],
    'regressor__regressor__max_depth': [None, 10]
}
rf_grid = GridSearchCV(rf_pipe, rf_param_grid, cv=3, scoring='neg_mean_absolute_error', n_jobs=-1)
rf_grid.fit(X_train, y_train)
print(f"Best RF params: {rf_grid.best_params_}")

c:\Programming\Machine Learning\Used Car Price Intelligence\.venv\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

Best RF params: {'regressor__regressor__max_depth': None, 'regressor__regressor__n_estimators': 100}

In [13]:
xgb_base = xgb.XGBRegressor(random_state=42)
xgb_tt = TransformedTargetRegressor(regressor=xgb_base, func=np.log1p, inverse_func=np.expm1)
xgb_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', xgb_tt)
])
xgb_param_grid = {
    'regressor__regressor__n_estimators': [50, 100],
    'regressor__regressor__learning_rate': [0.05, 0.1]
}
xgb_grid = GridSearchCV(xgb_pipe, xgb_param_grid, cv=3, scoring='neg_mean_absolute_error', n_jobs=-1)
xgb_grid.fit(X_train, y_train)
print(f"Best XGB params: {xgb_grid.best_params_}")

c:\Programming\Machine Learning\Used Car Price Intelligence\.venv\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

Best XGB params: {'regressor__regressor__learning_rate': 0.1, 'regressor__regressor__n_estimators': 100}

In [14]:
from sklearn.ensemble import VotingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [15]:
best_ridge = ridge_grid.best_estimator_
best_rf = rf_grid.best_estimator_
best_xgb = xgb_grid.best_estimator_

In [ ]:
ensemble_model = VotingRegressor(
    estimators=[
        ('ridge', best_ridge['regressor']), 
        ('rf', best_rf['regressor']), 
        ('xgb', best_xgb['regressor'])
    ],
    weights =[0.75,0.125,0.125]
)

final_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('ensemble', ensemble_model)
])

final_pipeline.fit(X_train, y_train)

predictions = final_pipeline.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print(f"-------Weighted Voting Ensemble-------")
print(f"Mean Absolute Error : Rs {int(mae):,}")
print(f"Root Mean Squared Error : Rs {int(rmse):,}")
print(f"R2 Score: {r2}")

c:\Programming\Machine Learning\Used Car Price Intelligence\.venv\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

-------Weighted Voting Ensemble-------
Mean Absolute Error : Rs 108,543
Root Mean Squared Error : Rs 638,407
R2 Score: -1.5769967408460643

In [17]:
import joblib
import os

model_dir = r"C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\models"
os.makedirs(model_dir, exist_ok=True)
model_path = os.path.join(model_dir, "arbitrage_model.pkl")

joblib.dump(final_pipeline, model_path)
print(f"Optimized model successfully saved to {model_path}")

Optimized model successfully saved to C:\Programming\Machine Learning\Used Car Price Intelligence\Used Car Arbitrage\models\arbitrage_model.pkl